name = "SimpleCropModel"
uuid = "f3ed3eca-5833-409f-abdd-79a7bdb2cb96"
authors = ["Jun Hyuk Jeon"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
